name: "Pull request"

on:
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest

  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup
        uses: actions/setup-go@v1
        with:
          go-version: "1.16"
      - name: install portaudio
        run: |
          sudo apt-get update && \
          sudo apt-get install portaudio19-dev
      - name: test
        run: make test

  build-macos:
    runs-on: macos-latest
    needs: [lint, test]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup
        uses: actions/setup-go@v1
        with:
          go-version: "1.16"
      - name: build
        run: |
          brew install pkg-config portaudio && \
          make build

  build-linux:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup
        uses: actions/setup-go@v1
        with:
          go-version: "1.16"
      - name: build
        run: |
          sudo apt-get update && \
          sudo apt-get install portaudio19-dev && \
          make build
